/**
 *************************************************************
 * @Author: LIANG YAN BIAO
 * @Date:   on 2020/05/25
 * @Last Modified by:   LIANG YAN BIAO
 * @Last Modified time: on 2020/05/25
 *************************************************************
 */
'use strict'

export const API_CHECK_IMG = 'api/check-img'
export const API_SMSCODE = 'api/smscode'
export const API_LOGIN = 'api/login'
export const API_LOGOUT = 'api/Logout'
export const API_USERINFO = 'api/info'
export const API_SET_USERINFO = 'api/setimgface'
export const API_RECEPTION = 'api/reception'
export const API_RECEPTION_LIST = 'api/reception/list'
export const API_RECEPTION_INFO = 'api/reception/info'
export const API_ACCOUNT_OFFSET = 'api/account/offset'
export const API_ADMIN_HOME = 'api/admin/home'
export const API_ADMIN_MANAGE_LIST = 'api/admin/manage/list'
export const API_ADMIN_MANAGE_FREEZELIST = 'api/admin/manage/freeze-list'
export const API_ADMIN_ADD = 'api/admin/add'
export const API_ADMIN_MANAGE_FREEZE = 'api/admin/manage/freeze'
export const API_ADMIN_EXAMINE = 'api/admin/examine'
export const API_ADMIN_EXAMINE_LIST = 'api/admin/examine/list'
export const API_ADMIN_PROFIT_LIST = 'api/admin/profit/list'
export const API_ADMIN_PROFIT_DETAIL = 'api/admin/profit/detail'
export const API_ADMIN_PROFIT_DETAILLIST = 'api/admin/profit/detail-list'
export const API_QRCODE_CREATE = 'api/qrcode/create'
export const API_QRCODE_REGISET = 'api/qrcode/regiest'
export const API_QRCODE_DETAIL = 'api/qrcode/detail'
export const API_ADMIN_MYCYSSTATE = 'api/admin/mycus-stat'
export const API_ADMIN_MYCYSCONSUME = 'api/admin/mycus-consume'
export const API_ADMIN_MYCYS = 'api/admin/mycus'
export const API_ADMIN_MYCYS_DETAIL = 'api/admin/mycus-detail'
export const API_ACCOUNT_INFO = 'api/account/info'
export const API_ACCOUNT_INFOID = 'api/account/info-id'
export const API_CHECKSTAND_STAT = 'api/checkstand/stat'
export const API_ACCOUNT_SEARCH = 'api/account/search'
export const API_ACCOUNT_LOGSAM = 'api/account/logs-am'
export const API_ACCOUNT_REWRADHOME = 'api/account/reward-home'
export const API_ACCOUNT_REWRADLIST = 'api/account/reward-list'
export const API_ADMIN_PROFIT_DAYDETAIL = 'api/admin/profit/day-detail'
export const API_ADMIN_PROFIT_CUSLIST = 'api/admin/profit/cus-list'
export const API_ADMIN_UPGRADE = 'api/admin/upgrade'
export const API_CHECKIN_LIST = 'api/checkin/list'
export const API_CHECKIN_ROOMLIST = 'api/checkin/room-list'
export const API_CHECKIN = 'api/checkin'
export const API_CHECKIN_COMFIRM = 'api/checkin/comfirm'
export const API_ADMIN_DELETE = 'api/admin/delete'
export const API_CHECKIN_DEL = 'api/checkin/delete'
export const API_CHECKSTAND_LIST = 'api/checkstand/list'
